Repository sepandhaghighi/samila, pull requests merged in 2021-11, with the labels that each got.

#70 Matplotlib Version Saving
  samila/functions.py
  samila/genimage.py
  samila/params.py
  test/warning_test.py
Labels: bug, enhancement

#71 Minor edits
  README.md
  samila/functions.py
  samila/genimage.py
  samila/params.py
  test/warning_test.py
Labels: documentation, enhancement

#72 Version 0.3
  .github/workflows/test.yml
  .github/workflows/test2.yml
  AUTHORS.md
  CHANGELOG.md
  README.md
  dev-requirements.txt
  otherfiles/images/4.png
  otherfiles/version_check.py
  samila/__init__.py
  samila/errors.py
  samila/functions.py
  samila/genimage.py
  samila/params.py
  setup.py
  test/error_test.py
  test/nft_upload_test.py
  test/overall_test.py
  test/warning_test.py
Labels: release
