Repository sepandhaghighi/samila, pull requests merged in 2021-10, with the labels that each got.

#67 Complex data
  samila/genimage.py
  test/overall_test.py
Labels: bug

#68 Discord badge
  CHANGELOG.md
  README.md
  setup.py
Labels: enhancement

#69 Python 3.10
  .github/workflows/test.yml
  CHANGELOG.md
  setup.py
Labels: test
