Repository sepandhaghighi/samila, pull requests merged in 2022-03, with the labels that each got.

#103 Gitcoin badge
  README.md
  otherfiles/gitcoin_btn.png
Labels: documentation

#104 Demo update
  .github/workflows/test.yml
  README.md
  examples/demo.ipynb
  otherfiles/notebook_check.py
Labels: documentation

#105 Version 0.5
  .github/workflows/test.yml
  AUTHORS.md
  CHANGELOG.md
  README.md
  dev-requirements.txt
  examples/demo.ipynb
  otherfiles/gitcoin_btn.png
  otherfiles/notebook_check.py
  otherfiles/version_check.py
  samila/functions.py
  samila/genimage.py
  samila/params.py
  setup.py
  test/nft_upload_test.py
  test/overall_test.py
Labels: release

#106 Add linewidth parameter
  CHANGELOG.md
  samila/functions.py
  samila/genimage.py
  samila/params.py
Labels: enhancement, new feature
