Repository sepandhaghighi/samila, pull requests merged in 2022-11, with the labels that each got.

#159 Marker Added
  CHANGELOG.md
  README.md
  examples/demo.ipynb
  otherfiles/images/9.png
  samila/__init__.py
  samila/functions.py
  samila/genimage.py
  samila/params.py
  test/function_test.py
  test/overall_test.py
Labels: enhancement

#161 Minor edits
  README.md
  setup.py
  test/overall_test.py
Labels: documentation, test

#162 Python 3.11 support
  .github/workflows/test.yml
  CHANGELOG.md
  setup.py
Labels: test

#163 Generate method optimization
  CHANGELOG.md
  samila/functions.py
  samila/genimage.py
  test/overall_test.py
  test/warning_test.py
Labels: performance

#164 Data/Config Upload to IPFS
  CHANGELOG.md
  README.md
  examples/demo.ipynb
  samila/functions.py
  samila/genimage.py
  test/nft_upload_test.py
Labels: new feature

#165 Plot Warning
  CHANGELOG.md
  samila/genimage.py
Labels: bug

#167 Test
  test/nft_upload_test.py
Labels: bug, test
