Repository sepandhaghighi/samila, pull requests merged in 2022-04, with the labels that each got.

#108 Depth parameter added
  CHANGELOG.md
  samila/functions.py
  samila/genimage.py
Labels: enhancement

#109 Link and Path fields added
  CHANGELOG.md
  samila/functions.py
  samila/params.py
  test/overall_test.py
Labels: enhancement, new feature

#112 Random mode modification
  CHANGELOG.md
  README.md
  samila/params.py
Labels: enhancement

#113 Version 0.6
  CHANGELOG.md
  README.md
  otherfiles/version_check.py
  samila/functions.py
  samila/genimage.py
  samila/params.py
  setup.py
  test/overall_test.py
Labels: release

#114 Test update
  CHANGELOG.md
  test/overall_test.py
Labels: test

#115 Random mode modification
  CHANGELOG.md
  samila/functions.py
  samila/params.py
Labels: enhancement

#117 Html colors support
  CHANGELOG.md
  samila/functions.py
  samila/params.py
  test/overall_test.py
Labels: enhancement

#119 Minor edits
  CHANGELOG.md
  README.md
  examples/demo.ipynb
  test/overall_test.py
Labels: documentation, test

#124 Random mode
  CHANGELOG.md
  README.md
  examples/demo.ipynb
  samila/functions.py
  samila/params.py
  test/function_test.py
  test/nft_upload_test.py
  test/overall_test.py
Labels: enhancement, new feature

#125 Equation warning
  CHANGELOG.md
  samila/functions.py
  samila/genimage.py
  samila/params.py
  test/warning_test.py
Labels: bug, enhancement
