Repository sepandhaghighi/samila, pull requests merged in 2022-05, with the labels that each got.

#126 Update test
  CHANGELOG.md
  samila/functions.py
  test/function_test.py
  test/overall_test.py
Labels: bug, test

#127 README updated
  README.md
Labels: documentation

#128 Version 0.7
  CHANGELOG.md
  README.md
  dev-requirements.txt
  examples/demo.ipynb
  otherfiles/version_check.py
  samila/functions.py
  samila/genimage.py
  samila/params.py
  setup.py
  test/function_test.py
  test/nft_upload_test.py
  test/overall_test.py
  test/warning_test.py
Labels: release

#129 Random mode modification
  CHANGELOG.md
  samila/params.py
Labels: enhancement

#131 Complement color
  CHANGELOG.md
  README.md
  examples/demo.ipynb
  samila/functions.py
  test/function_test.py
  test/overall_test.py
Labels: enhancement, new feature

#132 Set hex color format to lowercase
  samila/functions.py
  test/function_test.py
  test/overall_test.py
Labels: enhancement

#133 Transparent Feature Added
  CHANGELOG.md
  README.md
  examples/demo.ipynb
  samila/functions.py
  samila/genimage.py
  test/function_test.py
  test/overall_test.py
Labels: enhancement, new feature

#135 Warnings
  CHANGELOG.md
  samila/functions.py
  samila/params.py
  test/error_test.py
  test/function_test.py
  test/overall_test.py
  test/warning_test.py
Labels: enhancement
