Repository sepandhaghighi/samila, pull requests merged in 2022-01, with the labels that each got.

#80 Config json Added
  CHANGELOG.md
  README.md
  samila/errors.py
  samila/functions.py
  samila/genimage.py
  samila/params.py
  test/error_test.py
  test/function_test.py
  test/overall_test.py
  test/warning_test.py
Labels: enhancement

#82 Minor Edits Added
  CHANGELOG.md
  samila/functions.py
  samila/genimage.py
  test/overall_test.py
Labels: enhancement

#83 Minor edits
  samila/functions.py
  samila/genimage.py
Labels: enhancement

#84 Version 0.4
  .github/workflows/test.yml
  CHANGELOG.md
  README.md
  dev-requirements.txt
  otherfiles/images/7.png
  otherfiles/version_check.py
  samila/errors.py
  samila/functions.py
  samila/genimage.py
  samila/params.py
  setup.py
  test/error_test.py
  test/function_test.py
  test/nft_upload_test.py
  test/overall_test.py
  test/warning_test.py
Labels: release

#86 Minor edits
  CHANGELOG.md
  README.md
  otherfiles/images/3.png
Labels: enhancement

#87 Minor edits
  CHANGELOG.md
  README.md
Labels: documentation

#92 Demo notebook
  AUTHORS.md
  CHANGELOG.md
  examples/demo.ipynb
Labels: documentation, enhancement

#93 Random mode modification
  CHANGELOG.md
  samila/params.py
Labels: enhancement

#94 Depth parameter added to the nft_storage method
  CHANGELOG.md
  samila/functions.py
  samila/genimage.py
  samila/params.py
  test/nft_upload_test.py
Labels: enhancement

#95 Social media
  README.md
Labels: documentation
