Repository sepandhaghighi/samila, pull requests merged in 2022-09, with the labels that each got.

#147 Point colors doc
  CHANGELOG.md
  README.md
  examples/demo.ipynb
  otherfiles/images/8.png
Labels: documentation

#148 Anaconda workflow
  .github/workflows/publish_conda.yaml
  .github/workflows/publish_pypi.yml
  CHANGELOG.md
  README.md
  autopep8.bat
  autopep8.sh
  otherfiles/meta.yaml
  otherfiles/version_check.py
Labels: test

#149 Minor edits
  README.md
  examples/demo.ipynb
Labels: documentation

#150 Minor edits
  .github/CODE_OF_CONDUCT.md
  CHANGELOG.md
  README.md
  samila/functions.py
  setup.py
  test/function_test.py
Labels: documentation

#151 Error handling
  CHANGELOG.md
  samila/functions.py
  samila/params.py
  test/error_test.py
  test/overall_test.py
Labels: enhancement, test

#154 Version 0.9
  .github/CODE_OF_CONDUCT.md
  .github/workflows/publish_conda.yaml
  .github/workflows/publish_pypi.yml
  .github/workflows/test.yml
  CHANGELOG.md
  README.md
  autopep8.bat
  autopep8.sh
  dev-requirements.txt
  examples/demo.ipynb
  otherfiles/images/8.png
  otherfiles/meta.yaml
  otherfiles/samila_profile.py
  otherfiles/version_check.py
  samila/functions.py
  samila/genimage.py
  samila/params.py
  setup.py
  test/error_test.py
  test/function_test.py
  test/overall_test.py
Labels: release
