Repository sepandhaghighi/samila, pull requests merged in 2023-04, with the labels that each got.

#187 Version 1.1
  CHANGELOG.md
  README.md
  otherfiles/meta.yaml
  otherfiles/version_check.py
  samila/params.py
  setup.py
Labels: release

#189 Pillow
  CHANGELOG.md
  otherfiles/meta.yaml
Labels: dependencies

#190 Codecov
  .github/workflows/test.yml
  CHANGELOG.md
  dev-requirements.txt
Labels: test, dependencies

#191 Test warnings fixed
  CHANGELOG.md
  samila/functions.py
  samila/params.py
Labels: test
