Repository sepandhaghighi/samila, pull requests merged in 2024-08, with the labels that each got.

#218 Deprecation
  CHANGELOG.md
  README.md
  samila/functions.py
  samila/genimage.py
  samila/params.py
  test/nft_upload_test.py
  test/warning_test.py
Labels: enhancement, minor

#222 New `GenerateMode`
  README.md
  samila/genimage.py
  samila/params.py
  test/overall_test.py
Labels: enhancement, new feature

#223 New `GenerateMode`
  CHANGELOG.md
  README.md
  samila/genimage.py
  samila/params.py
  test/overall_test.py
Labels: enhancement
