Repository sepandhaghighi/samila, pull requests merged in 2025-04, with the labels that each got.

#257 Cite
  CHANGELOG.md
  README.md
Labels: documentation

#258 `Ubuntu-20.04` --> `Ubuntu-22.04`
  .github/workflows/publish_conda.yaml
  .github/workflows/publish_pypi.yml
  .github/workflows/test.yml
  CHANGELOG.md
  otherfiles/meta.yaml
  setup.py
Labels: documentation, test

#259 Type hint
  CHANGELOG.md
  otherfiles/samila_profile.py
  otherfiles/version_check.py
  samila/cli.py
  samila/functions.py
  samila/genimage.py
  setup.py
Labels: documentation, enhancement
